### ISSUE TITLE
dimension

### ISSUE THREAD

**Issue by matt574** [bvanheu/stratatools#3]
will this work for dimension canisters?
also where does the eeprom uid come from, is that viewable with your software from the bin dump?
im using the Arduino eeprom tool to dump it?
(one more) sorry im new to all this, will this work on windows. im installing Ubuntu right now but i have python and the arduino eeprom tool running on one of my windows machines.
thanks

**Comment by es4m0n** [comment]
Is it possibel to refill a dimension canister?

**Comment by HaveBlueXST** [comment]
es4m0n, yes, you can refill a Dimension cartridge.  Have a look at my tutorial:  http://haveblue.org/?p=1988
