### ISSUE TITLE
GPIO.4 mode to be changed from the default IN to OUT?

### ISSUE THREAD

**Issue by hjjayakrishnan** [bvanheu/stratatools#32]
Prior to $ sudo modprobe w1-gpio gpiopin=4 and $ sudo modprobe w1-ds2433, should the GPIO mode be set to OUT, by $ gpio mode 7 out ?

**Comment by HaveBlueXST** [comment]
No, you don't need to set mode on the pin prior to the modprobe commands, as the modules will take care of the pin configuration for you.
