### ISSUE TITLE
Unable to find device on bus pirate using bp_read.py [Windows]

### ISSUE THREAD

**Issue by alyra** [bvanheu/stratatools#33]
I'm on a windows 8 machine running Python 2.7.12 with pycrypto 2.6.1 installed. When trying to use the test file bp_read.py I am unable to find my EEPROM chip.

In cmd I use the command _python bp_read.py COM7 eeprom.bin_ and I've made sure that I'm connected to the correct COM port and the baud rate is set to 115200.

The following output is received:

_λ python bp_read.py COM7 eepromBin
Device found: None
Traceback (most recent call last):
  File "bp_read.py", line 138, in <module>
    raise(Exception("unable to find a device on this 1-wire bus"))
Exception: unable to find a device on this 1-wire bus_

I've tested the EEPROM chip with a OneWire sniffer and can find all of the data.
I've tested the buspirate with the hardware test on the dangerous prototype website with all OK

I cannot figure out why I'm unable to find my EEPROM chip.

My setup looks like this:

![img_1226](https://cloud.githubusercontent.com/assets/17012087/17753595/5ec37758-6485-11e6-8085-11a3938fa949.JPG)
![img_1227](https://cloud.githubusercontent.com/assets/17012087/17753596/5ec36d80-6485-11e6-9255-a7a62e3115f3.JPG)
![img_1228](https://cloud.githubusercontent.com/assets/17012087/17753597/5ec5dea8-6485-11e6-9485-9236445c495e.JPG)

**Comment by bvanheu** [comment]
won't fix as BusPirate is not the preferred option (use a raspberry pi).
