### ISSUE TITLE
Trouble With Rasp Pi UID Reading

### ISSUE THREAD

**Issue by swkmmm** [bvanheu/stratatools#51]
We have our Raspberry Pi set up like the example on the README.md. We go to enter the following commands:

$ sudo modprobe w1-gpio gpiopin=4
$ sudo modprobe w1-ds2433

It doesn't display anything. So we enter:

$ ls -l /sys/bus/w1/devices/w1_bus_master1

We get a list of files at that location but we do not get any chip information like the README.md shows. I have double checked our setup. The modules above are loaded. What am I missing?

**Comment by HaveBlueXST** [comment]
It sounds like you may have DeviceTree enabled, as that's the default on newer releases of Raspbian.

**Comment by swkmmm** [comment]
So we got to the point of being able to copy the eeprom to the local file. What tool do I use to decrypt it?

**Comment by HaveBlueXST** [comment]
Use stratasys-cli.py, just like the readme.md file.

**Comment by swkmmm** [comment]
$ ./stratasys-cli.py eeprom -t fox -e 6b0000014d476223 -i cartridge_dump.bin

We attempted to follow the above instructions but got an error. 

ImportError: No module name Crypto.Cypher

**Comment by 256FF** [comment]
You can find a detailed instruction here: [http://haveblue.org/?p=1988](url)

**Comment by Toblivar** [comment]
Make sure to install the pycrypto module, as it is dependent on that library.

**Comment by bvanheu** [comment]
Closing this issue as this is not a bug with the actual tool but support request.
