### ISSUE TITLE
refill Fortus MC900

### ISSUE THREAD

**Issue by kogi84** [bvanheu/stratatools#62]
hallo refill experts,
I am trying to create a eeprom(ds2433) for an Fortus 900MC with eeprom_create.... Therefore I use fox2 as maschine type, right? But what value for key-fragment I have to enter? What is the meaning of the parameter key-fragment? 
Thank you for your help!

**Comment by HyKECh** [comment]
https://github.com/bvanheu/stratatools/issues/26#issuecomment-162228733

**Comment by bvanheu** [comment]
key-fragment can be random, provided in hex. It is part of the key that is used to encrypt / decrypt.

Example of values:
```
0000000000000000
0102030405060708
ffffffffffffffff
```
