### ISSUE TITLE
Invalid checksums

### ISSUE THREAD

**Issue by woutervddn** [bvanheu/stratatools#9]
Hi I keep getting this error on all my eeproms... I tried to figure out how that came to be but failed...

Traceback (most recent call last):
  File "./stratasys-cli.py", line 228, in <module>
    app.run()
  File "./stratasys-cli.py", line 47, in run
    args.func(args)
  File "./stratasys-cli.py", line 125, in command_eeprom
    self._eeprom_info(args)
  File "./stratasys-cli.py", line 167, in _eeprom_info
    cartridge = m.decode(machine_number, args.eeprom_uid, cartridge_crypted)
  File "/home/pi/stratasys-master/stratasys/manager.py", line 74, in decode
    cartridge = self.unpack(cartridge_packed)
  File "/home/pi/stratasys-master/stratasys/manager.py", line 130, in unpack
    raise Exception("invalid content checksum: should have " + hex(struct.unpack("<H", str(cartridge_packed[0x40:0x42]))[0]) + " but have " + hex(self.checksum.checksum(cartridge_packed[0x00:0x40])))
Exception: invalid content checksum: should have 0x83f5 but have 0x5e57

Any thoughts?

**Comment by rhum1rhum1** [comment]
Hi guys,

First, thanks a lot bvanheu for your work :)

I have exactly the same problem for the decryption of canister for Fortus 900mc.
I can see the STRATASYS signature in the dump but I have the "invalid content checksum"...
Command line is : 
./stratasys-cli.py eeprom -t prodigy -e 490000017cbb0a23 -i eeprom

I try to write a new EEPROM (EEPROM Failure on the machine) and I try the different type of machine numbers with no sucess.

Any ideas?

Thanks.

**Comment by acca84** [comment]
Hello, i have the same problem with a dimension (prodigy) dump
I dumped the eeprom using an arduino and this tool : 
https://github.com/meawoppl/eepromTool-ds2433
my uid is 
2314857801000029ff
i reversed it to : 
ff2900000178851423
when i launch, under windows 10 : 
stratasys-cli.py eeprom -t prodigy -e ff2900000178851423 -i cartridge_dump.bin

i have this error

Did you find a solution please ?

**Comment by 256FF** [comment]
Hi, 
delete the "ff. It is unneccesary.
